/*
===============================================================================
Purpose: Customer Segmentation and Purchasing Behavior Analysis
===============================================================================

This query creates a customer summary report by combining customer information
with sales transactions. It calculates key business metrics that can be used
for customer analytics, reporting, and marketing strategies.

The query provides the following insights for each customer:
1. Customer details (name, country, age).
2. Purchase activity (number of orders, products purchased, quantities).
3. Revenue metrics (total sales, average order value, average monthly spend).
4. Customer lifetime information (first order, last order, spending duration).
5. Recency analysis (months since the customer's last purchase).
6. Customer segmentation:
      - VIP     : Customer has been buying for at least 12 months and has
                  spent more than 5000.
      - Regular : Customer has been buying for at least 12 months and has
                  spent 5000 or less.
      - New     : Customer has been buying for less than 12 months.
7. Age grouping for demographic analysis.
===============================================================================
*/
-- create view table 
create or alter view gold.analytics_customer AS
-- Create a CTE that aggregates all sales information for each customer
WITH base_customer_info AS
(
    SELECT
      
        c.customer_key,
        -- Combine first and last name into one column
        CONCAT(c.first_name, ' ', c.last_name) customer_name,
        c.country,
        -- Calculate customer's age based on birthdate
        DATEDIFF(YEAR, c.birthdate, GETDATE()) age,
        -- Total number of orders placed by the customer
        COUNT(s.order_number) order_number,
        -- Date of the customer's first purchase
        MIN(s.order_date) first_order,
        -- Date of the customer's most recent purchase
        MAX(s.order_date) last_order,
        -- Total number of products purchased
        COUNT(s.product_key) total_product,
        -- Total quantity of items purchased
        SUM(s.quantity) total_quantity,
        -- Total sales amount generated by the customer
        SUM(s.sales) total_sales

    FROM gold.fast_sales s
    LEFT JOIN gold.dim_customer c
        ON s.customer_key = c.customer_key

    -- Group by customer to calculate aggregated metrics
    GROUP BY
        c.customer_key,
        CONCAT(c.first_name, ' ', c.last_name),
        c.country,
        DATEDIFF(YEAR, c.birthdate, GETDATE())
)

SELECT
    customer_key,
    customer_name,
    country,
    age,
    order_number,
    total_quantity,
    total_product,
    total_sales,
    last_order,

    -- Number of months between the first and last purchase
    DATEDIFF(MONTH, first_order, last_order) total_spending_time_inmonth,

    -- Classify customers based on loyalty and spending
    CASE
        WHEN DATEDIFF(MONTH, first_order, last_order) >= 12
             AND total_sales > 5000 THEN 'VIP'
        WHEN DATEDIFF(MONTH, first_order, last_order) >= 12
             AND total_sales <= 5000 THEN 'reguler'
        ELSE 'new'
    END customer_sugmentation,

    -- Group customers into age categories
    CASE
        WHEN age < 25 THEN '25 and less'
        WHEN age BETWEEN 25 AND 45 THEN '25 - 45'
        WHEN age BETWEEN 46 AND 60 THEN '46 -60'
        ELSE 'above 60'
    END age_group,

    -- Number of months since the customer's last purchase
    DATEDIFF(MONTH, last_order, GETDATE()) recency,

    -- Average amount spent per order
    -- Return 0 to avoid division by zero
    CASE
        WHEN order_number = 0 THEN 0
        ELSE total_sales / order_number
    END avg_order_value,

    -- Average monthly spending over the customer's lifetime
    -- If all purchases happened in the same month, return total sales
    -- to avoid division by zero
    CASE
        WHEN DATEDIFF(MONTH, first_order, last_order) = 0
            THEN total_sales
        ELSE total_sales / DATEDIFF(MONTH, first_order, last_order)
    END avg_monthly_spend

FROM base_customer_info;
