/*
===============================================================================
 Product Performance Segmentation Analysis
===============================================================================

 Purpose:
 --------
 This query analyzes sales performance for each product and classifies products
 into performance segments (High Performers, Mid Range, and Low Performers).

 The query combines transactional sales data with product information to
 generate key business metrics that can be used for reporting, dashboards,
 and product performance analysis.

 Metrics Calculated:
 -------------------
 1. Total Customers       -> Number of unique customers who purchased the product.
 2. Total Orders          -> Number of unique orders containing the product.
 3. Total Sales           -> Total revenue generated by the product.
 4. Total Quantity        -> Total units sold.
 5. Total Price           -> Sum of product prices from sales transactions.
 6. Average Sales Price   -> Average selling price per unit.
 7. Recency               -> Number of months since the last sale.
 8. Lifespan              -> Number of months between the first and last sale.
 9. Product Segment       -> Categorizes products based on total sales:
                                - High Performers : Sales > 50,000
                                - Mid Range       : Sales between 10,000 and 50,000
                                - Low Performers  : Sales < 10,000
10. Average Sales per Order -> Average revenue generated per order.
11. Average Monthly Spend   -> Average monthly sales during the product lifespan.

 Business Use Cases:
 -------------------
 - Identify top-performing and underperforming products.
 - Support product portfolio analysis.
 - Build Power BI dashboards and executive reports.
 - Assist in inventory planning and sales strategy decisions.
===============================================================================
*/
CREATE OR ALTER VIEW  Product_Performance_Segmentation_Analysis AS
-- Extract sales transactions and combine them with product information
WITH base_info AS
(
	select 
		p.product_name,
		p.category,
		p.subcategory,
		p.product_line,
		f.customer_key,
		f.order_number,
		f.sales,
		f.quantity,
		f.price,
		p.cost,
		f.order_date
	from gold.fast_sales f
	LEFT JOIN gold.dim_product p
		-- Join sales transactions with product dimension
		on f.product_key = p.product_key
),

-- Aggregate data and calculate product-level metrics
calculation as (
	select 
		product_name,
		category,
		subcategory,
		product_line,

		-- Count unique customers who purchased the product
		count(distinct customer_key) total_customer,

		-- Count unique orders containing the product
		count(distinct order_number) total_orders,

		-- Total revenue generated by the product
		sum(sales) total_sales,

		-- Total quantity sold
		sum(quantity) total_quantity,

		-- Total of transaction prices
		sum(price) total_price,

		cost,

		-- Average selling price per unit
		round(avg(cast(sales as float) / nullif(quantity,0)),2) avg_sales,

		-- Number of months since the latest purchase
		DATEDIFF(MONTH, MAX(order_date), GETDATE()) recency,

		-- Number of months between first and last purchase
		datediff(month,min(order_date), max(order_date)) lifespan

	from base_info
	group by
		product_name,
		category,
		subcategory,
		product_line,
		cost
)

-- Return final product performance metrics and segmentation
select 
	product_name,
	category,
	subcategory,
	product_line,
	cost,
	total_customer,
	total_orders,
	total_sales,
	total_quantity,
	total_price,
	avg_sales,
	recency,
	lifespan,

	-- Classify products based on total sales
	case
		when total_sales > 50000 then 'high performers'
		when total_sales >= 10000 then 'mid range'
		else 'low performers'
	END segment_product ,

	-- Calculate average sales generated per order
	case 
		when total_orders = 0 then 0
		else total_sales / total_orders
	END AVG_sales_per_order,

	-- Calculate average monthly sales during the product lifespan
	CASE
        WHEN lifespan = 0 THEN total_sales
        ELSE total_sales / lifespan
    END avg_monthly_spend

from calculation
